version: '3.8'
services:
  web:
    build: .
    command: gunicorn main.wsgi --bind :8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    env_file:
      - .env
    # depends_on:
    #   - database
    # database:
    #   image: postgres:15.0-alpine
    #   env_file:
    #     - .env
    #   volumes:
    #     - ./postgres_data:/var/lib/postgresql/data
