# Generated by Django 4.1.2 on 2022-10-29 20:09

from django.db import migrations, models
import member.models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='member/avatar'),
        ),
        migrations.AddField(
            model_name='member',
            name='contact',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='department',
            field=models.CharField(blank=True, choices=[('CSE', 'Computer Science and Engineering'), ('ECE', 'Electronics and Communication Engineering'), ('EE', 'Electrical Engineering'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering'), ('IT', 'Information Technology'), ('BME', 'Biomedical Engineering'), ('AIML', 'Artificial Intelligence and Machine Learning'), ('BCA', 'Bachelor of Computer Applications'), ('MCA', 'Master of Computer Applications'), ('MBA', 'Master of Business Administration'), ('MTECH', 'Master of Technology'), ('BBA', 'Bachelor of Business Administration'), ('BSCCS', 'Bachelor of Science in Computer Science & Cyber Security'), ('CSBS', 'Computer Science and Business Systems')], max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(default='email@placeholder.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='member',
            name='graduation',
            field=models.IntegerField(default=member.models.get_current_year),
        ),
        migrations.AddField(
            model_name='member',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='name',
            field=models.CharField(default='Ashok Kumar', max_length=254),
        ),
        migrations.AddField(
            model_name='member',
            name='payment_image',
            field=models.ImageField(blank=True, null=True, upload_to='member/payment'),
        ),
        migrations.AddField(
            model_name='member',
            name='section',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='student_id',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='whatsapp',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='member',
            table='phoenix_member',
        ),
    ]
