name: deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  publish-phoenix-backend-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: phoenix-nsec
          password: ${{ secrets.TOKEN }}
      - name: Build the phoenix-backend Docker image
        run: |
          docker build . --tag ghcr.io/phoenix-nsec/phoenix-backend:latest
          docker push ghcr.io/phoenix-nsec/phoenix-backend:latest
